spring:
  application:
    name: ragdemo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gpt-oss:20b-cloud
      embedding:
        model: nomic-embed-text
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection: pdfs
        use-tls: false
        initialize-schema: true
  #      redis:
#        host: localhost
#        port: 6379
#        db: 0
#        password: ""
#        index-name: embedding
  data:
    mongodb:
      uri: mongodb://localhost:27017/rag
