spring:
  application:
    name: ragdemo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gpt-oss:20b-cloud
      embedding:
        model: gpt-oss:20b-cloud
    vectorstore:
      redis:
        host: localhost
        port: 6379
        db: 0
        password: ""
        index-name: vector_index
        path-name: embedding
  data:
    mongodb:
      uri: mongodb://localhost:27017/rag_db
