spring:
  application:
    name: ragdemo
  ai:
#    openai:
#      api-key: anyone
#      base-url: http://127.0.0.1:8000/v1
#      chat:
#        model: gemma4:e2b
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gpt-oss:20b-cloud
        options:
          temperature: 0.7
      embedding:
        model: nomic-embed-text
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection: pdfs
        use-tls: false
        initialize-schema: true
  #      redis:
#        host: localhost
#        port: 6379
#        db: 0
#        password: ""
#        index-name: embedding
  data:
    mongodb:
      uri: mongodb://localhost:27018/rag
  autoconfigure:
    exclude:
#      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration
#      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
